### ISSUE TITLE
Add batch reading support

### ISSUE THREAD

**Issue by bt90** [AudriusButkevicius/pfilter#5]
Blocks https://github.com/syncthing/syncthing/issues/7824

**Comment by bt90** [comment]
https://www.bountysource.com/issues/99985461-add-batch-reading-support

**Comment by bt90** [comment]
@AudriusButkevicius don't forget to claim your bounty 😉

**Comment by AudriusButkevicius** [comment]
still shows up as open in bountysource, so can't claim it.
